:idprefix:
:idseparator: -
ifndef::env-site,env-github[]
:toc: left
:toclevels: 3
endif::[]

toc::[]

== Deprecation notices

The following features are being deprecated and will be unsupported in
an upcoming version of Sync Gateway.

* *Bucket shadowing* has been deprecated since 1.4 and will be
unsupported in an upcoming version of Couchbase Mobile. The recommended
approach to perform operations on the bucket dedicated to Couchbase
Mobile is to use the Sync Gateway REST API.

== New Features

* No conflicts mode
(link:../../../guides/sync-gateway/config-properties/index.html#2.0/databases-foo_db-allow_conflicts[`databases.$db.allow\_conflicts`])
* Expiry value for local documents managed by Sync Gateway
(link:../../../guides/sync-gateway/config-properties/index.html#2.0/databases-foo_db-local_doc_expiry_secs[`databases.$db.local\_doc\_expiry\_secs`])

== Upgrading

Starting in Sync Gateway 2.0, Sync Gateway’s design documents include
the version number in the design document name. In this release for
example, the design documents are named `_design/sync_gateway_2.0` and
`_design/sync_housekeeping_2.0`.

On startup, Sync Gateway will check for the existence of these design
documents, and only attempt to create them if they do not already exist.
Then, Sync Gateway will wait until views are available and indexed
before starting to serve requests. To evaluate this, Sync Gateway will
issue a `stale=false&limit=1` query against the Sync Gateway views
(channels, access and role_access).

If the view request exceeds the default timeout of 75s (which would be
expected when indexing large buckets), Sync Gateway will log additional
messages and retry. The logging output will look like this:

[source,text]
----
14:26:41.039-08:00 Design docs for current SG view version (2.0) found.
14:26:41.039-08:00 Verifying view availability for bucket default...
14:26:42.045-08:00 Timeout waiting for view "access" to be ready for bucket "default" - retrying...
14:26:42.045-08:00 Timeout waiting for view "channels" to be ready for bucket "default" - retrying...
14:26:42.045-08:00 Timeout waiting for view "role_access" to be ready for bucket "default" - retrying...
14:26:44.065-08:00 Timeout waiting for view "access" to be ready for bucket "default" - retrying...
14:26:44.065-08:00 Timeout waiting for view "role_access" to be ready for bucket "default" - retrying...
14:26:44.065-08:00 Timeout waiting for view "channels" to be ready for bucket "default" - retrying...
14:26:44.072-08:00 Views ready for bucket default.
----

Sync Gateway 2.0 will *not* automatically remove the previous design
documents. Removal of the obsolete design documents is done via a call
to the new
link:../admin-rest-api/index.html#/server/post__post_upgrade[`/{db}/_post_upgrade`]
endpoint in Sync Gateway’s Admin REST API. This endpoint can be run in
preview mode (`?preview=true`) to see which design documents would be
removed. To summarize, the steps to perform an upgrade to Sync Gateway
2.0 are:

1.  Upgrade one node in the cluster to 2.0, and wait for it to be
reachable via the REST API (for example at http://localhost:4985/).
2.  Upgrade the rest of the nodes in the cluster.
3.  Clean up obsolete views:
* *Optional* Issue a call to `/_post_upgrade?preview=true` on any node
to preview which design documents will be removed. To upgrade to 2.0,
expect to see "sync__gateway" and "sync__housekeeping" listed.
* Issue a call to `/post_upgrade` to remove the obsolete design
documents. The response should indicate that "sync__gateway" and
"sync__housekeeping" were removed.

== GitHub issues

*Performance Improvements*

* https://github.com/couchbase/sync_gateway/issues/1383[*#1383*] Nginx
load balancer needs plugins to detect db offline state.
* https://github.com/couchbase/sync_gateway/issues/1850[*#1850*] Avoid
duplicate parsing of HTTP query string
* https://github.com/couchbase/sync_gateway/issues/2410[*#2410*] SG gets
into a 100% cpu state, where restart is the only recovery
* https://github.com/couchbase/sync_gateway/issues/2871[*#2871*] Review
bucket_gocb concurrent op limits
* https://github.com/couchbase/sync_gateway/issues/2928[*#2928*]
Optimize document unmarshalling for GetDoc

*Enhancements*

* https://github.com/couchbase/sync_gateway/issues/744[*#744*] When try
to put nonexistent document with rev: Document revision conflict
* https://github.com/couchbase/sync_gateway/issues/955[*#955*] Support
group reduce queries
* https://github.com/couchbase/sync_gateway/issues/1280[*#1280*]
Auto-expire unused _local checkpoint documents
* https://github.com/couchbase/sync_gateway/issues/1580[*#1580*] Use
latest version of Otto
* https://github.com/couchbase/sync_gateway/issues/1720[*#1720*]
Replication inaccurate 403 forbidden
* https://github.com/couchbase/sync_gateway/issues/1850[*#1850*] Avoid
duplicate parsing of HTTP query string
* https://github.com/couchbase/sync_gateway/issues/2354[*#2354*] Windows
service wrapper should write to a configurable stderr log file
* https://github.com/couchbase/sync_gateway/issues/2709[*#2709*]
Conflict-free mode (allow_conflicts:false)
* https://github.com/couchbase/sync_gateway/issues/3123[*#3123*] Log
_sync:seq on startup
* https://github.com/couchbase/sync_gateway/issues/3136[*#3136*]
Inter-document compression in BLIP replicator
* https://github.com/couchbase/sync_gateway/issues/3168[*#3168*] Move
allow_conflicts out of unsupported config

*Bugs*

* https://github.com/couchbase/sync_gateway/issues/1003[*#1003*] SG with
bucket shadowing doesn't work properly after CB restarted
* https://github.com/couchbase/sync_gateway/issues/1047[*#1047*] Runtime
panic while running tests on Jenkins
* https://github.com/couchbase/sync_gateway/issues/1406[*#1406*]
Feedtype=DCP not working sometimes
* https://github.com/couchbase/sync_gateway/issues/1488[*#1488*]
Rebalance -in a CBS node results in timeouts which manifests as empty
changes feed
* https://github.com/couchbase/sync_gateway/issues/1720[*#1720*]
Replication inaccurate 403 forbidden
* https://github.com/couchbase/sync_gateway/issues/2108[*#2108*] Missing
sequences in _changes feed causing sg-replicate missing documents
replication
* https://github.com/couchbase/sync_gateway/issues/2223[*#2223*] Wrong
name being set for users
* https://github.com/couchbase/sync_gateway/issues/2371[*#2371*] Logging - "Replicate" works when in *.json but not when you PUT _logging
* https://github.com/couchbase/sync_gateway/issues/2383[*#2383*] Channel
cache missing data when request instantiating cache times out
* https://github.com/couchbase/sync_gateway/issues/2410[*#2410*] SG gets
into a 100% cpu state, where restart is the only recovery
* https://github.com/couchbase/sync_gateway/issues/2441[*#2441*]
RedHat/Centos 6 'initctl restart sync_gateway' does not work as expected
* https://github.com/couchbase/sync_gateway/issues/2458[*#2458*] Log
rotation skipping BLIP keys
* https://github.com/couchbase/sync_gateway/issues/2489[*#2489*] XATTRs - Error unmarshalling doc
* https://github.com/couchbase/sync_gateway/issues/2497[*#2497*] XATTRS:
Getting doc after restart fails
* https://github.com/couchbase/sync_gateway/issues/2505[*#2505*] XATTRs:
View not returning results after restart
* https://github.com/couchbase/sync_gateway/issues/2521[*#2521*] XATTRs:
GET on doc after deletion returns inconsistent responses
* https://github.com/couchbase/sync_gateway/issues/2717[*#2717*] SG Blip
handler not reloading user channels
* https://github.com/couchbase/sync_gateway/issues/3048[*#3048*] Panic
when attempting to make invalid update to a conflicting document
* https://github.com/couchbase/sync_gateway/issues/3049[*#3049*] Allow
non-winning tombstone revisions when running with allow_conflicts=false
