:idprefix:
:idseparator: -
ifndef::env-site,env-github[]
:toc: left
:toclevels: 3
endif::[]

toc::[]

== Deprecation notices

The following features are being deprecated and will be unsupported in
an upcoming version of Sync Gateway.

* *Bucket shadowing* has been deprecated since 1.4 and will be
unsupported in an upcoming version of Couchbase Mobile. The recommended
approach to perform operations on the bucket dedicated to Couchbase
Mobile is to use the Sync Gateway REST API.

== New Features

* No conflicts mode
(link:../../../guides/sync-gateway/config-properties/index.html#2.0/databases-foo_db-allow_conflicts[`databases.$db.allow\_conflicts`])
* Expiry value for local documents managed by Sync Gateway
(link:../../../guides/sync-gateway/config-properties/index.html#2.0/databases-foo_db-local_doc_expiry_secs[`databases.$db.local\_doc\_expiry\_secs`])

== Upgrading

Starting in Sync Gateway 2.0, Sync Gateway’s design documents include
the version number in the design document name. In this release for
example, the design documents are named `_design/sync_gateway_2.0` and
`_design/sync_housekeeping_2.0`.

On startup, Sync Gateway will check for the existence of these design
documents, and only attempt to create them if they do not already exist.
Then, Sync Gateway will wait until views are available and indexed
before starting to serve requests. To evaluate this, Sync Gateway will
issue a `stale=false&limit=1` query against the Sync Gateway views
(channels, access and role_access).

If the view request exceeds the default timeout of 75s (which would be
expected when indexing large buckets), Sync Gateway will log additional
messages and retry. The logging output will look like this:

[source,text]
----
14:26:41.039-08:00 Design docs for current SG view version (2.0) found.
14:26:41.039-08:00 Verifying view availability for bucket default...
14:26:42.045-08:00 Timeout waiting for view "access" to be ready for bucket "default" - retrying...
14:26:42.045-08:00 Timeout waiting for view "channels" to be ready for bucket "default" - retrying...
14:26:42.045-08:00 Timeout waiting for view "role_access" to be ready for bucket "default" - retrying...
14:26:44.065-08:00 Timeout waiting for view "access" to be ready for bucket "default" - retrying...
14:26:44.065-08:00 Timeout waiting for view "role_access" to be ready for bucket "default" - retrying...
14:26:44.065-08:00 Timeout waiting for view "channels" to be ready for bucket "default" - retrying...
14:26:44.072-08:00 Views ready for bucket default.
----

Sync Gateway 2.0 will *not* automatically remove the previous design
documents. Removal of the obsolete design documents is done via a call
to the new
link:../admin-rest-api/index.html#/server/post__post_upgrade[`/{db}/_post_upgrade`]
endpoint in Sync Gateway’s Admin REST API. This endpoint can be run in
preview mode (`?preview=true`) to see which design documents would be
removed. To summarize, the steps to perform an upgrade to Sync Gateway
2.0 are:

1.  Upgrade one node in the cluster to 2.0, and wait for it to be
reachable via the REST API (for example at http://localhost:4985/).
2.  Upgrade the rest of the nodes in the cluster.
3.  Clean up obsolete views:
* *Optional* Issue a call to `/_post_upgrade?preview=true` on any node
to preview which design documents will be removed. To upgrade to 2.0,
expect to see "sync__gateway" and "sync__housekeeping" listed.
* Issue a call to `/post_upgrade` to remove the obsolete design
documents. The response should indicate that "sync__gateway" and
"sync__housekeeping" were removed.

=== View replacement

==== Installation and upgrade

On startup, Sync Gateway will check for the existence of these design
documents, and only attempt to create them if they do not already exist.
Then, Sync Gateway will wait until views are available and indexed
before starting to serve requests. To evaluate this, Sync Gateway will
issue a `stale=false&limit=1` query against the Sync Gateway views
(channels, access and role_access).

Installation will follow the same approach implemented in 2.0 for view install/upgrade:
Index names will include an index version suffix

On Sync Gateway startup, it will check for existence of required index versions, and create them if not present.

As part of the existence check, SG will also check if num_replica for the existing indexes matches the value specified in SG’s config.  If not, will drop and recreate the index.

Note: Need to document the scenario where different SG nodes specify different values for num_replica, and get stuck in drop/create battle.

On Sync Gateway startup, will verify index readiness (via query) before starting Sync Gateway’s REST API /db/_post_upgrade endpoint is used to remove obsolete index definitions, and is run after SG cluster upgrade is complete

As in the view case, Sync Gateway requires the existence of both the previous and current index definitions during an upgrade (that involves changes to the index definitions).  This is required to support zero-downtime upgrade of a Sync Gateway cluster, but need to review whether this is a larger concern for index node sizing.
